"""
Jasper Wang
A01362031
"""
import narrative.dialogue
import gameplay.character
from game_utils.render_text import print_text_line
from gameplay.level import play_level


def opening_sequence(level: int, character: dict) -> None:
    """
    Play the opening sequence of the game.

    :param character: a game character represented by a dictionary
    :precondition: character is a game character generated by the make_character() function in this module
    :postcondition: play the opening sequence, no data is modified and no value is returned
    """
    narrative.dialogue.play_dialogues_from_file_path(f"assets/dialogues/level{level}.txt", character)


def game():
    character = gameplay.character.make_character()
    for level in range(1, 3):
        character['X-coordinate'] = 0
        character['Y-coordinate'] = 0
        opening_sequence(level, character)
        character = play_level(level, character)
        if character is None:
            return
    end_game_message(character)


def end_game_message(character: dict) -> None:
    """
    Print the end game message based on the character's status

    :param character: a game character represented by a dictionary
    :precondition: character is a game character generated by the make_character() function in this module
    :postcondition: print the end game message, no data is modified and no value is returned
    """
    if character["Wisdom"] > character["Fury"]:
        print_text_line(
            "With wisdom as your guide, you have woven a path of insight and harmony through a world of turmoil, leaving a legacy of enlightenment and peace that will echo through ages."
        )
    else:
        print_text_line(
            "In a world craving balance, your path, fueled by unchecked fury, has left a trail marked by turmoil and "
            "conflict, a stark reminder of the cost of unbridled wrath."
        )


def main():
    game()


if __name__ == "__main__":
    main()
