import random

from utils import render_text


def check_for_monsters():
    """
    Determine whether a foe is present

    :postcondition: determine if a foe is present by comparing equality between 0 with generated random integer
    :return: a Boolean value of True if foe is present, False otherwise
    """
    random_number = random.randint(0, 3)
    if random_number == 0:
        return True

    return False


# TODO: Change docstrings
def play_monster_encounter(character):
    """
    Start a test_game number guessing test_game where user has to guess the randomly generated number between 1 and 5

    :param character: a test_game character
    :precondition: character is a test_game character generated by the make_character() function in this module
    :postcondition: 1 HP is deducted from character if user guesses incorrectly, no data is modified otherwise
    :return: None
    """
    render_text.print_text_line("!>>> !!! ALERT: MONSTER ENCOUNTER !!! <<<")
    # with K as kill
    # if user use guess: they gain wisdom
    # if user use kill, they gain anger

    # if character wisdom is high, range becomes lower
    lower = 1
    upper = 5

    if character["Wisdom"] > 30:
        upper = 3

    secret_number = random.randint(lower, upper)
    guess = input(
        f"Enter a number between {lower} and {upper} inclusive to deterred the monster, or type 'K' to kill the monster: "
    )

    if guess == "K":
        render_text.print_text_line(
            "You killed the monster ruthlessly. Though you are unharmed, you feel an anger inside brewing."
        )
        render_text.print_text_line("!You gained 5 Fury")
        character["Fury"] += 5
        return

    while not (guess.isdigit() and int(guess) in range(1, upper + 1)):
        render_text.print_text_line(
            f"!Invalid entry, please enter a number between {lower} and {upper} inclusive: "
        )
        guess = input()

    if int(guess) == secret_number:
        render_text.print_text_line("You succesfully deterred the monster!")
        render_text.print_text_line("$You gained 5 Wisdom!")
        character["Wisdom"] += 5
    else:
        character["Essence"] -= 5
        render_text.print_text_line(f"You failed, the monster attacked you and ran away.")
        render_text.print_text_line("!You just lost 5 Essence Point")
