name: Create Release with Python Bundle

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

jobs:
  create-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Create zip bundle
      run: |
        zip -r jasper-single-user-dungeon-${{ github.event.inputs.version }}.zip . \
          -x "*.git*" "*.github*" "*__pycache__*" "*.pyc" "*.pyo" "*.pyd" \
          "*.so" "*.egg-info*" "*dist*" "*build*" "*.DS_Store*"
    
    - name: Upload ZIP to Release
      uses: softprops/action-gh-release@v2
      with:
        name: ${{ github.event.inputs.version }}
        tag_name: ${{ github.event.inputs.version }}
        files: ./jasper-single-user-dungeon-${{ github.event.inputs.version }}.zip
