name: Create Release with Python Bundle

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

jobs:
  create-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Create zip bundle
      run: |
        zip -r jasper-single-user-dungeon-${{ github.event.inputs.version }}.zip . \
          -x "*.git*" "*.github*" "*__pycache__*" "*.pyc" "*.pyo" "*.pyd" \
          "*.so" "*.egg-info*" "*dist*" "*build*" "*.DS_Store*"
    
    - name: Create Release
      uses: elgohr/Github-Release-Action@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        title: Release ${{ github.event.inputs.version }}
        tag: ${{ github.event.inputs.version }}
        body: |
          ## Changes
          - Automated release of Python bundle
          
          ## Installation
          1. Download the zip file
          2. Extract to your desired location
          3. Run the Python application
        assets: jasper-single-user-dungeon-${{ github.event.inputs.version }}.zip
